name: TKTowns
main: io.github.wispoffates.minecraft.tktowns.TKTowns
version: 0.0.1
commands:
  tkt:
    description: List help for TKTowns.
    usage: /<command>
    permission: tktowns.tkt
    permission-message: You do not have permission to tktowns.tkt.
  tkt_town:
    description: List current town information. Create/Delete towns. Dontate/Withdraw from town bank.
    usage: /<command> [list/create/delete/donate/withdraw/balance]
    aliases: tktown
    permission: tktowns.town
    permission-message: You do not have permission to tktowns.town.
  tkt_realestate:
    description: List/Create/Sell/Lease/Rent/Buy real estate plot.
    usage: /<command> <list/create/buy/sell/lease/rent> <real estate name>
    aliases: tkreal
    permission: tktowns.realestate
    permission-message: You do not have permission to tktowns.realestate.
  tkt_outpost:
    description: Create/Delete outposts for town.
    usage: /<command> <create/delete> <outpost name>
    aliases: tkout
    permission: tktowns.outpost
    permission-message: You do not have permission to tktowns.outpost.
  tkt_resident:
    description: List/add/delete Residents from your town.
    usage: /<command> <add|remove|list> [player]
    aliases: tkres
    permission: tktowns.resident
    permission-message: You do not have permission to tktowns.resident. 